name: Extract C64 Music
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install 64tass
        run: |
          sudo apt-get update
          sudo apt-get install -y 64tass

      - name: Assemble ASM files
        run: |
          mkdir -p output
          for file in *.asm; do
            # uses Ocean macros
            64tass --quiet --ascii -i "$file" -lib ocean_assembler_directives.txt -o "output/${file%.asm}.prg" || echo "Skipping $file"
          done

      - name: Organize files
        run: |
          mkdir -p output
          cp *.prg output/ || echo "No extra prg giles in root"

      - name: Upload Binaries
        uses: actions/upload-artifact@v4
        with:
          name: compiled-music
          path: output/
